# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=30
separator=false
markup=none

# CPU usage
#
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[cpu_usage]
command=$HOME/.config/i3/scripts/cpu.sh
interval=5
markup=pango
#min_width=CPU: 100.00%
#separator=false

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
command=$HOME/.config/i3/scripts/memory.sh
#separator=false
interval=10
markup=pango

# Disk usage
#
# The directory defaults to $HOME if the instance is not specified.
# The script may be called with a optional argument to set the alert
# (defaults to 10 for 10%).
[disk]
command=$HOME/.config/i3/scripts/disk.sh
#instance=/mnt/data
interval=240
markup=pango

[network]
command=$HOME/.config/i3/scripts/network.sh
instance=tun0
interval=5
markup=pango

# Battery indicator
#
# The battery instance defaults to 0.
#[battery]
#label=BAT
#label=⚡
#instance=1
#interval=30

# Temperature
#
# Support multiple chips, though lm-sensors.
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
#[temperature]
#label=TEMP
#interval=10

# Date Time
#
[time]
#color=#9FE697
command=$HOME/.config/i3/scripts/time.sh
interval=1
min_width= Wednesday, 30 September 2026  00:00:00x
align=right
markup=pango
#align=right
#min_width=            Thursday, 30 September 2017
