# Minimal XRender setup for a responsive VMware guest.
backend = "xrender";
vsync = false;
shadow = false;
fading = false;
inactive-opacity = 1.0;
frame-opacity = 1.0;
detect-client-opacity = false;
unredir-if-possible = true;
